[package]
name = "peparse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.26"
bytes = "1.0.1"
hex = "0.4.3"
bitflags = "1.2.1"

[dependencies.segsource]
path = "../../segsource/segsource"
features = ["memmap", "async", "bytes"]
version = "0.1.0"

[dependencies.peparse-internal-macros]
path = "../macros"
version = "0.1.0"
